### ISSUE TITLE
Create Function to Open MXD

### ISSUE THREAD

**Issue by insect1285** [Geosyntec/gisutils#3]
Please create a function that will accept a string (e.g., a path).  This function would then assign the MXD using arcpy.mapping to a variable and then print the name/path back if all tests pass.

Please write this function into the script "openMap.py".  Include notes as necessary and try/except statements to deal with possible errors in the path, such as a file unable to be opened or a corrupt/bad MXD file.

Include a series of test functions as a separate module that will try to break your function and return ugly python errors.  If you get an ugly python error, try to correct for it in your function with either a clean error message or other work-around.

Expected usage is python openMap.py "Some String"

Expected result is an error or MXD path returned to user.

Feel free to ask me or others for help.

**Comment by phobson** [comment]
closed via d13e555e624b095d0453fc65c0cf0345b46f85f8

**Comment by phobson** [comment]
see also:  https://github.com/Geosyntec/gisutils/commit/d13e555e624b095d0453fc65c0cf0345b46f85f8#diff-0e1bb4a3b02c143a01158ae349091ff8R113
